### ISSUE TITLE
Provide a procedure to renew certficates

### ISSUE THREAD

**Issue by bsctl** [clastix/kamaji-etcd#17]
Currently, the self generated CA certificate has 5 years of lifetime and other certificates have 1 year. Provide a procedure/script to renew certificates on a live setup without service disruption.

**Comment by ptx96** [comment]
Hi @bsctl

it is not possible to directly reproduce the [etcd_job_postinstall_1.yaml](https://github.com/clastix/kamaji-etcd/blob/master/charts/kamaji-etcd/templates/etcd_job_postinstall_1.yaml) logic, due to the admission webhook `"vdatastoresecrets.kb.io"` restricting the deletion of secrets for security reason:

```
Error from server (the Secret is used by the following kamajiv1alpha1.DataStores and cannot be deleted (certs-etcd)): admission webhook "vdatastoresecrets.kb.io" denied the request: the Secret is used by the following kamajiv1alpha1.DataStores and cannot be deleted (certs-etcd
```

**Comment by prometherion** [comment]
We can rework this on Kamaji side, or allowing to add a set of labels that will skip the validation just for the renew procedure, something has `datastore.kamaji.clastix.io/certificate=renew`.
