### ISSUE TITLE
cfssl issue with arm64

### ISSUE THREAD

**Issue by tibeer** [clastix/kamaji-etcd#37]
Hi there!

I wanted to test clastix/kamaji but unfortunately I only have access to arm64 machines.
During the deployment I noticed that the script below won't run due to architecture incompatibilities.
https://github.com/clastix/kamaji-etcd/blob/master/scripts/certs-renew.sh#L28

It turns out that cfssl in version 1.6.1 is not available for arm64 platforms. I don't know if a patch would break things and if the pinned version is intentional. If not I would create a PR to bump the version :)

Kind regards
Tim

**Comment by tibeer** [comment]
Never mind, the deployment itself seems to use latest. For some reason initial etcd certs-job still fails with this message:
```
cfssl exec /bin/bash: exec format error
```

**Comment by prometherion** [comment]
@tibeer unfortunately, we have such a big dependency on `cfssl`.

Unless we use a different tool to generate resources, this issue is something we cannot cope with.

Rather, since we're aware of that, we could mark the `cfssl` pods to run on `amd64` machines, in order to share in a more declarative way the requirements, as well as contribute to the documentation this: are you available to work on this?

**Comment by tibeer** [comment]
That won't help much though if you are running an only arm64 cluster :D Therefore I think i'll skip on this for now. Sorry for that, but thanks a lot for the great explanation 🚀
